### ISSUE TITLE
Error in VT service for openxml doc types

### ISSUE THREAD

**Issue by ed4wg** [CybercentreCanada/assemblyline-service-virustotal#17]
I noticed this error in our vt service logs. It seems like it is specific to the openxml doc types like docx, but I'm not 100% sure on that. 

Also, we have the `extract` service configured to extract all office docs like so: `document/office/.*` instead of the default. When i revert extract to the default `accepts` configuration, we do not see this error in VT. 

Also, the user does not see any error in the UI. This is just showing up in the logs. 

`
"level": "ERROR", "logger": "assemblyline.service.virustotal" }, "process": { "pid": "27" }, "message": "(44H8t036g7KsY2habpaVim/74ac8c0faa6898f5ba1feeb6725f381b228ffb8af714fb91b521259d601dcdc1): Problem applying data to given model: [category] timeout not in the possible values: {'suspicious', 'failure', 'undetected', 'malicious', 'type-unsupported'}"}
`

**Comment by cccs-rs** [comment]
Should now be resolved in 4.3.1.stable1 😎
